# Generated by Django 5.2.12 on 2026-04-03 15:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(max_length=18)),
                ('contato', models.CharField(blank=True, max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('especialidade', models.CharField(choices=[('eletrica', 'Elétrica'), ('civil', 'Civil'), ('hidraulica', 'Hidráulica'), ('pintura', 'Pintura'), ('outros', 'Outros')], max_length=32)),
                ('telefone', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'verbose_name': 'parceiro',
                'verbose_name_plural': 'parceiros',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('orcamento', 'Orçamento'), ('ativo', 'Ativo'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado')], default='orcamento', max_length=20)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_entrega_prevista', models.DateField(blank=True, null=True)),
                ('orcamento_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos', to='core.cliente')),
            ],
            options={
                'verbose_name': 'projeto',
                'verbose_name_plural': 'projetos',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=16)),
                ('categoria', models.CharField(choices=[('material', 'Material'), ('mao_de_obra', 'Mão de obra'), ('licenca', 'Licença'), ('fixo', 'Fixo'), ('outros', 'Outros')], max_length=32)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_pagamento', models.DateField()),
                ('parceiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='core.parceiro')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='core.projeto')),
            ],
            options={
                'verbose_name': 'gasto',
                'verbose_name_plural': 'gastos',
                'ordering': ('-data_pagamento',),
            },
        ),
    ]
