# Generated by Django 5.2.12 on 2026-04-03 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='data_aprovacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='descricao_escopo',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='OrcamentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=14)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('material', 'Material'), ('mao_de_obra', 'Mão de obra')], max_length=20)),
                ('parceiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamento_itens', to='core.parceiro')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento_itens', to='core.projeto')),
            ],
            options={
                'verbose_name': 'item de orçamento',
                'verbose_name_plural': 'itens de orçamento',
                'ordering': ('projeto', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RelatorioAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal')], max_length=16)),
                ('descricao', models.TextField()),
                ('fotos_url', models.TextField(blank=True, help_text='URLs das fotos (ex.: JSON ou uma URL por linha).')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_atividade', to='core.projeto')),
            ],
            options={
                'verbose_name': 'relatório de atividade',
                'verbose_name_plural': 'relatórios de atividade',
                'ordering': ('-id',),
            },
        ),
    ]
