# Generated by Django 5.2.12 on 2026-04-03 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        ('licenciamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='licenca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='licenciamento.licenca'),
        ),
    ]
