# Generated by Django 5.2.12 on 2026-04-03 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_projeto_orcamento_relatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgaoEmissor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('url_portal', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'órgão emissor',
                'verbose_name_plural': 'órgãos emissores',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Licenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=128)),
                ('data_protocolo', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('alerta', 'Alerta'), ('expirada', 'Expirada')], default='pendente', max_length=16)),
                ('link_portal', models.URLField(blank=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='licencas/pdfs/')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencas', to='core.projeto')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licencas', to='licenciamento.orgaoemissor')),
            ],
            options={
                'verbose_name': 'licença',
                'verbose_name_plural': 'licenças',
                'ordering': ('data_vencimento',),
            },
        ),
    ]
