# Generated by Django 5.2.12 on 2026-04-03 23:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenciamento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('lida', models.BooleanField(default=False)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_licenciamento', to=settings.AUTH_USER_MODEL)),
                ('licenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='licenciamento.licenca')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ('-data_envio',),
                'indexes': [models.Index(fields=['licenca', 'destinatario', 'lida', 'data_envio'], name='licenciamen_licenca_d84204_idx')],
            },
        ),
    ]
